### ISSUE TITLE
add boost gauge and custom dashboard

### ISSUE THREAD

**Issue by scruggyj** [synman/AdaptiveTuner#15]
For example add additional layouts or cutomizable layouts for the dash board.

For my personal eveeyday use I would like just afr, water temp and boost (not currently on the display).

That would only be 3 gauges displayed and would allow them to be larger as well.

That would be awesome addition to an already awesome tool.   Thanks

**Comment by synman** [comment]
working on a boost/vacuum gauge now in place of showing MAP in kPA

Additional / customizable layouts is something I will look into in the future.

**Comment by synman** [comment]
Will be included in 1.2.10
