### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by peaatearr** [synman/AdaptiveTuner#20]
Logging stopped working some update ago.
My last log was from November 2014. 
Recently tested the SSI-4 update, and no log was generated. Adaptive Tuner folder on native memory card does not have new log. No other Adaptive Tuner folder was found elsewhere (i.e. memory card).

**Comment by synman** [comment]
hmm....

Do you ever actually "share" the log using the log button in the top right corner of the action bar?  Please try that if not.  

I suspect you may never be actually sharing the log and since I don't have logic to automatically share / save it on shutdown it is never being written out to a file.

It should be in /sdcard/AdaptiveTuner  or similar.

**Comment by peaatearr** [comment]
This is what I have for options. I have never seen a "share" option.

**Comment by synman** [comment]
Go into Alerts & Logging Preferences --> Log All Data (at the end of the list) ... select it.  When you return to Adaptive Tuner you should see this icon in the upper right corner.

![sgozy](https://cloud.githubusercontent.com/assets/1299716/6932585/64d93058-d7e9-11e4-8dc4-d7cc846f141f.png)

Click it when you're ready to stop logging.  There are a number of intents you act on from texting the file to emailing it, posting it on Facebook :) , etc.

I'm tempted to treat this as a legit bug and ensure I always write out the log on onDestroy() of the Main activity and/or disconnect.

**Comment by peaatearr** [comment]
I got it. I've always had that checked before.
That symbol only shows up when the adaptronic is connected. I was checking
the software without it connected.

In this case is there a duration or amount of data that is recorded? I'm
asking I guess for a max amount of data recorded. i.e track sessions of 20
minutes. Would starting adaptive tuner going out, and then clicking the
share button at the end of the session (20 minutes later) would it record
all data within that 20 minutes?

Not quite sue about the intent thing you are talking about.

**Comment by synman** [comment]
You are correct.  So long as Adaptive Tuner remains running (even in the background) all data for that 20 minutes would be saved to a file and you'd be given the option to Share it via email/etc upon hitting the share button.

I am going code additional logic for saving the log to a file (without sharing) on exit / disconnect which means you should never lose any data.

**Comment by peaatearr** [comment]
Shell, that was how it was previously, Auto logging/saving.
I've never had to use this "Share" feature. I have a few logs that were
generated just by opening adaptive tuner, which I really enjoyed the
feature in case something happened, and I wanted to look back.

**Comment by synman** [comment]
will fix it with this next release

**Comment by synman** [comment]
* Save log on exit / disconnect if one exists 

included in 1.2.12

**Comment by timkent** [comment]
Hi Shell,

Is it possible to make it a preference for if "* KPA_TO_PSI" is applied or not?  Not sure if I'm alone but I prefer to see the measurements in metric if possible.

I can tackle it if you want?

Cheers

**Comment by synman** [comment]
reopening to add toggle for UOM.  Tim, do you want the toggle to apply to both the logs and UI?

**Comment by synman** [comment]
I’ll take it.  I was actually scratching my head why folks were so interested in PSI for fuel/oil pressure when the reference values are kPa.  I’ll make it a toggle, no problem

**Comment by timkent** [comment]
Yes please, I think it changing both is less confusing.

Thanks Shell!

**Comment by synman** [comment]
included in 1.2.13

**Comment by peaatearr** [comment]
Took the car out for a spin earlier today. Log saving automatically works.
Haven't checked the log on the computer yet.
Fuel P and Oil P displaying correctly, or in normal range.
This should be on 1.2.12 updated the app in the afternoon of 4/1/15.
