### ISSUE TITLE
Feature Request: Skin/Look

### ISSUE THREAD

**Issue by peaatearr** [synman/AdaptiveTuner#21]
Would like to have Analog and Digital readouts together. 
Warning lights/threshold lights
Water T to mimic curent Air T. Added range would be wonderful. 

If Adaptive Tuner can mimic this, it would be even better:
https://play.google.com/store/apps/details?id=jp.co.nippon_seiki.advance.meter.adstyle

**Comment by synman** [comment]
yeah, not going to happen any time soon unless a contributor comes along with way too much time on their hands to do the coding.

You never know, I may tackle this one day, but no promises as it is a considerable amount of work.

**Comment by synman** [comment]
doing some basic reskinning of the Adaptive Monitor tab with legit digital readouts

**Comment by synman** [comment]
done for now ... may re-open in the future
